name: _deleteImage

on:
  workflow_call:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Restore Cash Module
        uses: actions/cache/restore@v4
        with:
          path: "node_modules"
          key: module-${{ github.sha }}
      - name: Pre-Generate
        run: yarn pre-del
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Scheduled Delete Images
          delete-branch: true
          title: Scheduled Delete Images
