name: _install

on:
  workflow_call:

permissions:
  contents: write

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Restore Cash Main
        uses: actions/cache/restore@v4
        with:
          path: .
          key: main-repo-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Install dependencies
        run: yarn
      - name: Cash Module
        uses: actions/cache/save@v4
        with:
          path: "node_modules"
          key: module-${{ github.run_id }}-${{ github.run_attempt }}
