name: _install

on:
  workflow_call:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Restore Cash Main
        uses: actions/cache/restore@v4
        with:
          path: .
          key: main-repo-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Restore Cash Module
        uses: actions/cache/restore@v4
        with:
          path: "node_modules"
          key: module-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Install libvips
        run: sudo apt-get update && sudo apt-get install -y libvips-dev
      - name: Pre-Generate
        run: yarn pre-a
      - name: Cash Assets
        uses: actions/cache/save@v4
        with:
          path: "assets"
          key: assets-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Cash Public
        uses: actions/cache/save@v4
        with:
          path: "public"
          key: public-${{ github.run_id }}-${{ github.run_attempt }}
