name: _pull_request

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Restore Cash Module
        uses: actions/cache/restore@v4
        with:
          path: "node_modules"
          key: module-${{ github.sha }}
      - name: Restore Cash PAAPI
        uses: actions/cache/restore@v4
        with:
          path: "src/temp/amazon.json"
          key: paapi-${{ github.sha }}
      - name: Restore Cash Assets
        uses: actions/cache/restore@v4
        with:
          path: "assets"
          key: assets-${{ github.sha }}
      - name: Restore Cash Public
        uses: actions/cache/restore@v4
        with:
          path: "public"
          key: public-${{ github.sha }}
      - name: Delete Image
        run: yarn pre-del
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Scheduled Pull Request
          delete-branch: true
          title: Scheduled Pull Request
