name: deploy-v20

on:
  repository_dispatch:
    types:
      - my-custom-type
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    uses: tibdex/github-app-token@v1
    with:
      app_id: ${{ secrets.MY_APP_ID }}
      private_key: ${{ secrets.PRIVATE_KEY }}
  install:
    uses: ./.github/workflows/_install.yml
  pre:
    needs: install
    uses: ./.github/workflows/_pre.yml
  deploy:
    needs: pre
    uses: ./.github/workflows/_deploy.yml
