name: deploy-v20

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types:
      - my-custom-type
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
