name: deploy-v20

on:
  repository_dispatch:
    types:
      - my-custom-type
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  get-main-repo:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.generate.outputs.token }}
    steps:
      - name: Checkout Core Repo
        uses: actions/checkout@v4
      - name: Generate GitHub Apps token
        id: generate
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          ./script.sh
      - name: Checkout Main Repo
        uses: actions/checkout@v4
        with:
          # プライベートリポジトリを指定
          repository: syachi-hoko-maru/trpg-system-code
          # 秘密鍵を指定
          ssh-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
          token: ${{ steps.generate.outputs.token }}
          ref: main
      - name: Cash Main Repo
        uses: actions/cache/save@v4
        with:
          path: .
          key: main-repo-${{ github.run_id }}-${{ github.run_attempt }}
  install:
    needs: get-main-repo
    uses: ./.github/workflows/_install.yml
  pre:
    needs: install
    uses: ./.github/workflows/_pre.yml
  deploy:
    needs: pre
    uses: ./.github/workflows/_deploy.yml
  close:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Revoke GitHub Apps token
        env:
          GITHUB_TOKEN: ${{ job.get-main-repo.outputs.token }}
        run: |
          curl --location --silent --request DELETE \
            --url "${GITHUB_API_URL}/installation/token" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}"
