name: cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types:
      - my-custom-type
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Pre-Generate
        run: yarn pre

      - name: Generate
        run: yarn generate

      - name: After-Generate
        run: yarn after

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
