name: deploy-with-paapi

on:
  workflow_dispatch:
  schedule:
    - cron: "30 19 * * *"
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  paapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn
      - name: Use PA API
        run: yarn paapi
  deploy:
    needs: paapi
    uses: ./.github/workflows/deploy.yml
