name: deploy-with-paapi

on:
  workflow_dispatch:
  schedule:
    - cron: "30 19 * * *"
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  install:
    uses: ./.github/workflows/_install.yml
  pre:
    needs: install
    uses: ./.github/workflows/_pre.yml
  paapi:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Restore Cash Module
        uses: actions/cache/restore@v4
        with:
          path: "node_modules"
          key: module-${{ github.sha }}
      - name: Use PA API
        env:
          ACCESS_KEY: ${{secrets.ACCESS_KEY}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
        run: yarn paapi
      - name: Cash
        uses: actions/cache/save@v4
        with:
          path: "src/temp/amazon.json"
          key: paapi-${{ github.sha }}
  deploy:
    needs:
      - pre
      - paapi
    uses: ./.github/workflows/_deploy.yml
